name: 
  base-data-science
channels:
  - conda-forge
  - default
dependencies:
  - python=3.8
  - numpy=1.19.0
  - matplotlib=3.3.1
  - pandas=1.1.2
  - scikit-learn=0.23
  - seaborn=0.11.0
  - jupyterlab=2.2.8
  - requests=2.24.0
  - cookiecutter=1.7.2
  - pytest=6.1.0